### ISSUE TITLE
add guidance on how the issuers choose how to blind claim names

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#132]
user has 2 SD-JWTs from the same issuer, same blinded claim names can be used to correlate the user.
advice to have a fresh blinded claim name for each credential.

**Comment by sbutterfield** [comment]
Instead of opening a new issue from our conversation this morning - here is the excerpt & suggestion from the document we discussed:
## blinding the attribute name
First off, maybe it's informational or maybe it's specified - issuers should not include "secrets" in claim labels. If a label for something is actually a secret, it should be treated as such. That said, I get that this scenario must be addressed. Sensitive predicates or graduated disclosure contexts can benefit from this capability. 

It seems to me that the most useful and easy algorithm to implement is to use the same hash algorithm + salt for the node value to blind the label where: SALTED LABEL = HASH_ALGO(LABEL + SALT)
Of course, this assumes that specific guidance is included for best practice salt generation (fresh entropy gathering for each attribute block salt, sufficient bits of entropy, etc.) for strong cryptographic outcomes.

"_sd": {
  "9-J2445a_p91...": {
    "h": "Y823Kowek92...", // b64url
    "l": "name"
    "s": "H82leq3!4...", // re-use salt
    "id": "did:jwk:894fa94hg10AOEe82…#0", //claim specific DID URL binding
    "v": "Slim Shady"
  }
}

In this representation, the salted hash of the label's value ("name") "9-J2445a_p91..." can be addressed directly by the digest "h" value in compact form: 
"_sd": {
  "9-J2445a_p91...": "Y823Kowek92..."
}

Side-note:
Informative statements that recommend large sd-jwt claim sets should be 'broken down' into much smaller sets, or individual claims, then wrapped and sealed as a JWP may be better than including too many claims in an sd-jwt.

**Comment by danielfett** [comment]
Right now, it is RECOMMENDED that a random string is chosen for the blinded claim name. HMAC(salt, claim-name) and HASH_ALGO(LABEL + SALT) would be fine as well, but there's more room for errors, especially as holders/verifiers might expect a specific format and then reject an SD-JWT when, e.g., the issuer chose a wrong encoding or similar.

I don't see a real advantage of using HMAC/HASH_ALGO for the blinded claim name. 

I therefore propose to stick with the current recommendation. We should stress that a fresh random value must be chosen for each claim in each issued credential.

**Comment by sbutterfield** [comment]
@danielfett it's not super clear to me how: 
```
SD-CLAIMS = (
    CLAIM-NAME-PLACEHOLDER: DIGEST-DERIVATION(SALT, CLAIM-VALUE, CLAIM-NAME)
)*
```
would alleviate your concerns here: _"but there's more room for errors, especially as holders/verifiers might expect a specific format and then reject an SD-JWT when, e.g., the issuer chose a wrong encoding or similar"_

Maybe I'm missing something obvious but I don't see much difference in how holders & verifiers would treat these various approaches. They still have to reconcile with the encoding and/or hashing algorithms expressed in the security envelope.

**Comment by sbutterfield** [comment]
I see, thanks for explaining that. I'm fine with option 1 if the goal is to reduce cognitive complexity for the application developers - it makes sense.

**Comment by Sakurann** [comment]
PR #155 and PR #158
