### ISSUE TITLE
make holder binding JWT first in the combined formats for presentation

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#253]
Would it make sense to change the order of strings in the combined formats for presentation, so that the holder binding JWT is first? that way it is easier to understand whether it is a combined format for presentation or issuance?

**Comment by bc-pi** [comment]
My initial reaction here is no.  Saying which (HB first vs. last) is easier is pretty subjective. And a breaking change in the format shouldn't be undertaken without pretty compelling reason.

**Comment by danielfett** [comment]
That's an idea that Torsten has been entertaining for quite a while, but I still see no compelling reason to do so. 

The main purpose would be to allow some receiver to distinguish between issuance and presentation, but ...
  1. ... I don't see in what situations a receiver would not already know what to expect (iss. vs. pres.).
  2. ... if the receiver needs to distinguish, it can just look at the last part of the iss. or presentation to figure out what to do. The effort with the new proposal is roughly the same, and in both cases one cannot just feed the presentation or issuance to a naive JWT library.
     - Processing with the current format: "Split by ~, then if the last part is empty or contains a dot, it's a presentation; otherwise: issuance." 
     - With the proposed change: "Split by ~, decode the first JWT and look at some header or claim telling you what to do."

**Comment by TakahikoKawasaki** [comment]
My SD-JWT library (authlete/[sd-jwt](https://github.com/authlete/sd-jwt)) for Java parses a given string as @danielfett describes above.

- The implementation is here -> [SDCombinedFormatParser.java](https://github.com/authlete/sd-jwt/blob/main/src/main/java/com/authlete/sd/SDCombinedFormatParser.java)
- Test cases are here -> [SDCombinedFormatTest.java](https://github.com/authlete/sd-jwt/blob/main/src/test/java/com/authlete/sd/SDCombinedFormatTest.java)

If the proposed change results in requiring SD-JWT libraries to parse JWTs in order to judge whether the given string is Issuance or Presentation, the current specification is better.

My SD-JWT library intentionally avoids parsing JWTs so that the library can be used combinedly with any existing JWT library. This intention is explicitly written in the [SD-JWT section](https://github.com/authlete/sd-jwt#sd-jwt) in the README of the library. The current order can give this flexibility to developers.

**Comment by Sakurann** [comment]
I think Taka is right. even if HB-JWT will be the first in order, the receiving entity will now have to parse that JWT to check if it is sd-jwt or a hb-jwt...
