### ISSUE TITLE
Creation of decoys

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#260]
Why `create the decoy digests by hashing over a cryptographically secure random number` (and use `the same digest function as for. the Disclosures`)? 

Feedback received why apply a cryptographic hash function over the output of a cryptographically secure RNG. That is a bit excessive. However, having read a bit about the topic. Since there is no cryptographically secure RNG of the operating system, it is possible to analyze the decoys to determine entropy / detect patterns, thereby undermining security. but hashing the RNG output just makes this process a lot slower. It simply adds computational overhead to any attempt to brute force it. 

It seems to that the text simply "inherited" the security best practice from generating sensitive material like tokens. In the context of decoys the risks are perhaps not that great, but it is not like adding a SHA256 step results in any performance hit

**Comment by danielfett** [comment]
The application of the hash function is a simple and computationally cheap way to reduce the chances that decoys become easily distinguishable from the real digests, for example because of

 * bad implementation of the nonce (e.g., insufficient length or insufficient entropy), or
 * properties of the hash function that make the output distinguishable from nonces (although practically used hash functions probably don't have this problem).

For example, without applying the hash, if the hash function is switched from SHA256 to SHA512, the developer needs to adapt the choice of the nonce accordingly. With the proposed method, the nonce can just always be, e.g., a 128 bit integer that gets hashed to whatever the hash function defines.
