### ISSUE TITLE
alg=none in SD-JWT-R

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-selective-disclosure-jwt#28]
Comment from @b---c. 
> https://www.ietf.org/archive/id/draft-fett-oauth-selective-disclosure-jwt-00.html#section-5-3.2.1 -> "Check that the presentation consists of six .-separated elements; if holder binding is not required, the last element can be empty." Seems to imply that alg=none would be used for an unsigned SD-JWT Release while other parts of the doc seem to have just encoded SVC.

**Comment by Sakurann** [comment]
need to discuss if we want to allow unsigned SD-JWT-R - don't think alg=none would be a good idea.

+ need clarify the six .-separated elements text

**Comment by danielfett** [comment]
Why would alg=none not be a good idea?

**Comment by selfissued** [comment]
I agree with @danielfett that it's context-specific whether "alg"="none" is appropriate - just like it's context-specific whether any other signing and/or encryption algorithms are appropriate.

We should not be making algorithm choices in the basic SD-JWT spec.  Profiles are free to do that.

**Comment by PieterKas** [comment]
@danielfett, @selfissued don't we have evidence that alg=none is a dangerous option and leads to security issues as a result of implementation errors?

**Comment by bc-pi** [comment]
SD-JWT should disallow alg=none.

Allowing the SVC (or whatever it becomes) to be unsigned is okay but can just be one chunk of base64url encoded JSON.

**Comment by Sakurann** [comment]
> SD-JWT should disallow alg=none. 
yes, we agreed SD-JWT must be signed.

but will SD-JWT-R allow alg=none..? or we say that when SD-JWT-R is unsigned it is not a JWT, but a JSON object?

**Comment by tlodderstedt** [comment]
I'm not sure it is a good idea to go down the "use an unsigned assertion instead of a plain object" to solve that problem again. 

The requirement at hand is to release a credential with selective disclosure in cases where there is no cryptographic holder binding. That might for example mean, the credential is bound to certain claims of the holder, e.g. name and dob. That is normal practise for a lot of credentials today in the real world (including diplomas) and it is the design used by the UE Covid Certificate. So I don't think it is an edge case. 

I suggest to come up with a technically sound solution that also does not give people a vector to attack our proposal.  A plain JSON object seems to be a reasonable solution.

**Comment by selfissued** [comment]
If we ever want SD-JWT-R to be signed, then it should be a JWT.  If we also want it to be able to be unsigned, then the JWT should use alg:none when unsigned.  If we decide that SD-JWT-R should never be signed, then it should always be base64url-encoded JSON.  But again, if it's sometimes signed, that's exactly what alg:none is for, and why we included it the JWS spec.

alg:none is not an attack vector in this use case, since the claims are protected by the hashes.

**Comment by tlodderstedt** [comment]
I think, if we want unsigned releases, the release shall be a JSON object. If the release shall be signed, that same JSON Object could be the payload of a JWS aka a JWT.

**Comment by selfissued** [comment]
If I'm understanding you correctly, Torsten then you're advocating having either base64url-encoded JSON (one segment) or a signed JWT with three segments (header, payload, signature).  It's that format inconsistency that alg:none is intended to prevent, since it would also be three segments.

That doesn't answer the question of whether there's ever a reason to sign the SD-JWT-R.  For simplicity purposes, I would assert that it should never be signed.  (Then the alg:none discussion would become moot.)

**Comment by PieterKas** [comment]
Signing the SD-JWT-R makes sense if we want to verify the holder binding or want to prevent impersonation or replay. These artefacts will be stolen, just like bearer tokens are being stolen and exfiltrated, so requiring signatures in at least some of the cases will stop that attack vector.

**Comment by christianpaquin** [comment]
I'm catching up on this thread, going back to my implementation. I've never used `alg=none` before, and in the bearer token case, I must say it feels weird to append an extra JWS header with `alg=none`, the SVC as payload, and an empty signature (i.e., currently proposed SD-JWT-R: `<iss header>.<SD-JWT-payload>.<iss sig>.<holder header (alg=none)>.<SVC>.<empty string>`) I feel that the spec should only define the SVC format as a JSON object, and say that if the SD-JWT is not key bound, then the SVC may be base64url encoded and attached to the SD-JWT as a 4th part.

How is the holder-binding for normal JWT accomplished, in the various industry profiles? Would you typically create a separate JWS using the holder key, and concatenate the issuer's and the holder's JWS?

**Comment by Sakurann** [comment]
`If verifier is supposed to check the signature, do not accept alg=none`. When to check the signature is up to the Verifier's trust framework/policy, etc.)

with alg=none, attacker can remove the signature from a valid SD-JWT and replace it with alg=none, but one can make the same mistake even if JSON is used because attacker can remove both header and the signature.
it adds more confusion because now we need to explain both JSON and JWT.

**Comment by danielfett** [comment]
See also https://datatracker.ietf.org/doc/html/rfc8725#section-3.2


>    That said, if a JWT is cryptographically protected end-to-end by a
>    transport layer, such as TLS using cryptographically current
>    algorithms, there may be no need to apply another layer of
>    cryptographic protections to the JWT.  In such cases, the use of the
>    "none" algorithm can be perfectly acceptable.  The "none" algorithm
>    should only be used when the JWT is cryptographically protected by
>    other means.  JWTs using "none" are often used in application
>    contexts in which the content is optionally signed; then, the URL-
>    safe claims representation and processing can be the same in both the
>    signed and unsigned cases. 
>

**Comment by Sakurann** [comment]
PR #155

**Comment by Sakurann** [comment]
PR merged
