### ISSUE TITLE
kb_jwt in JSON serialisation

### ISSUE THREAD

**Issue by alenhorvat** [oauth-wg/oauth-selective-disclosure-jwt#325]
_Holder adds the key kb_jwt at the top-level of the serialized JWS with a string value containing the Key Binding JWT as described in [Section 5.10](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-05.html#kb-jwt)._

Once the JWS is signed, the key binding is ensured via the signature. The current proposal asks the user to sign 2x
1. signature is the "signature" of the payload and protected header
2. is the key binding JWT which actually proves the same

Should the kb_jwt be removed from the JSON serialised JWS?

**Comment by danielfett** [comment]
I'm not sure I understand your point. The first signature is the signature by the Issuer, the second one by the Holder. This is the same for all data formats. Who is 'user' in your case?

**Comment by alenhorvat** [comment]
In our cases we're not concerned about the size since information is always retrieved from the server or sent to the server directly. Simplest is to ask the wallet providers just to sign the whole thing and that's it.

But I agree, if there are cases where the size is critical, e.g., sharing the payload via redirects, optimisation can applied.

**Comment by paulbastian** [comment]
An argument that I see for linking the disclosures (probably as hash) into the payload of the KB-JWT is, that:
- a holder could later dispute that he actually released certain claims as disclosures 
- a verifier could dispute that he actually received certain disclosures
To me this is a little weird because right now the signature gives us non-repudiation while the disclosures are repudiable.

**Comment by bc-pi** [comment]
PR #344 removes the kb_jwt from the JSON serialization and so will address this issue once merged. 

Issue #346 is to separately track adding an option for a hash of the SD-JWT and Disclosures in KB-JWT
