### ISSUE TITLE
typ:example+sd-jwt everywhere?

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-selective-disclosure-jwt#365]
Do we want the header `"typ":"example+sd-jwt"` in every example? I'm honestly not sure but wanted to ask b/c that looks like it's going to be the result from https://github.com/openwallet-foundation-labs/sd-jwt-python/pull/10 upstream.

**Comment by danielfett** [comment]
We should make a conscious decision about this, especially regarding the examples in the appendix.

**Comment by Sakurann** [comment]
for example 4a, it must be `vc+sd-jwt` because it is required by sd-jwt vc spec [here](https://openid.github.io/oid4vc-haip-sd-jwt-vc/draft-oid4vc-haip-sd-jwt-vc.html#name-format-identifier) (it should be clearer in sd-jwt vc spec, because there is no `MUST`). 
For example 4b, it should be `vc+ld+json+sd-jwt`, but it can also be kept example+sd-jwt. because [W3C vc-jose-cose spec](https://www.w3.org/TR/vc-jose-cose/#securing-json-ld-verifiable-credentials-with-jose) says `The typ header parameter SHOULD be vc+ld+json+sd-jwt.`.

**Comment by bc-pi** [comment]
good with the state of things currently for typ values
