### ISSUE TITLE
Encapsulation instead of concatenation of data structures.

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-selective-disclosure-jwt#37]
The concatenation of data structures may result in reliability problems (the data structures may get dissociated), or could be an entry point for an attacker (swapping out data structures, especially if there is no binding between them).

It may be interesting to consider encapsulation instead of concatenation. In that approach the issuer will generate a SD-JWT that contains the hashes and the SVC. The SVC will be encrypted with the holders public key, so that a verifier cannot access the SVC data. 

The holder will decrypt the SVC structure in the SD-JWT, decide which claims to present, and then include them in the SD-JWT-R. To avoi concatenation of the SD-JWT and SD-JWT-R, the SD-JWT can include the SD-JWT as an attribute. The result is a larger data structure, but it is all in one place, bound together, reducing the risk of accidental or malicious dissosiation. 

Something like:

SD-JWT = (hashes, SVC encrypted with holders public key)
SD-JWT-R = (disclosed claims, SD, JWT)

Then:

1. Issuer sends SD-JWT to Holder
2. Holder verifies SD-JWT, decrypts SVC, selects attributes to disclose, generate SD-JWT-R (which now includes the SD-JWT)
3. Verifier verifies SD-JWT-R (JD-SWT is encapsulated in the SD-JWT, the SD-JWT does include the SVC, but it is privacy protected, so no risk of unauthorised disclosure).

With encapsulation, the same information gets passed around. Encrypting the SVC with the holders public key allows it to be included in the SD-JWT, without risk of unauthorised disclosure to the verifier when the SD-JWT is processed by the verifier. Encapsulating the SD-JWT in the SD-JWT-R binds the two structures together and removes any risks of dissociating of the data structures.

**Comment by Sakurann** [comment]
very interesting. there is step 0 where the holder needs to send a encPubKey to the Issuer so that the Issuer can encrypt the SVC, which should not be the same as the signPubKey used to sign SD-JWT-R for holder binding. 

would you still want to bind SVC and SD-JWT as proposed in #31?

**Comment by danielfett** [comment]
- Sending 'unnecessary' encrypted data to the verifier is something we should avoid in my opinion. It makes the privacy of the claims depending on the strength of the encryption. We have seen weak encryption keys and leaked encryption keys in the past. If a verifier stores the encrypted values, it can try to decrypt them later on (forward secrecy), for example, after it turns out that the encryption algorithm is broken. 
- This makes implementations depend on JWE libraries. In my experience, JWS in libraries is much more mature and available than JWE. We should not make this spec depend on JWE.
- Larger data structure: base64 in base64 plus the encryption.

Overall, this proposal adds a lot of security concerns.

I do not see how manipulating the SVC or disassociating it from the SD-JWT leads to practical security problems. Unless we find practical concerns, I would propose to stick with the current approach.

**Comment by selfissued** [comment]
Per my comment https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/36#issuecomment-1153865303 , encapsulation results in unnecessary space bloat, which we should avoid.

**Comment by Sakurann** [comment]
the guidance on how to link the structures has been addressed in several PRs. 

However, keeping this open to discuss if we want to add an option to encrypt II-Disclosures Object (former SVC) - @danielfett ?

**Comment by Sakurann** [comment]
Editors believe that encapsulating approach would significantly complicate the approach, while the risk of the mapping between hashes and disclosures seems to be significantly low based on the initial implementation feedback
