### ISSUE TITLE
Add Test suite for SD-JWT

### ISSUE THREAD

**Issue by lukasjhan** [oauth-wg/oauth-selective-disclosure-jwt#416]
HI! I and @yunseorim1116 made a Test suite project for checking SD-JWT implementation.
You can check it here: https://github.com/lukasjhan/sd-jwt-test-api
It was written in TypeScript. It is in API server format and is distributed using docker.

I'm curious about your opinions on this project. 
If this is okay, How about write it in a standard document or put it in README?

Thank you

**Comment by bc-pi** [comment]
Thanks @lukasjhan, it's great to see this kind of work developing. It's not the kind of thing that would be appropriate in an IETF document, however. And it doesn't really fit very well with the "SD-JWT Implementations" of this README but maybe a line there with a name that qualifies it as a test server rather than actual implementation. Something like:

 * TypeScript: [SD-JWT Testing API server](https://github.com/lukasjhan/sd-jwt-test-api)

assuming @danielfett and @Sakurann are okay with that though...

**Comment by bc-pi** [comment]
Go ahead with a PR as such, @lukasjhan.

**Comment by lukasjhan** [comment]
Thank you I'll open a PR :)

**Comment by bc-pi** [comment]
> Thank you I'll open a PR :)

@lukasjhan can you do this please?

**Comment by lukasjhan** [comment]
@bc-pi sorry for late response :) I created a PR
