### ISSUE TITLE
SD-JWT Parser requires saving the base64 encoded values?

### ISSUE THREAD

**Issue by samuelgoto** [oauth-wg/oauth-selective-disclosure-jwt#532]
I ran into this problem while writing a parser for SD-JWT and a presenter that does the -KB parts. I'm not sure if this is a real problem,  but figured I should ask here.

I'm not sure if I did this correctly, but I think I couldn't find a way to avoid saving the base64 encoded values to reconstruct the SD-JWT and present it, because the JSON serialization isn't normalized (somewhat related to #531, except I don't think this is just a small and editorial problem, but an ergonomic one).

Here are some steps on how to reproduce the problem I'm facing preparing a sd-jwt for presentation:

1) Get an `sd-jwt`
2) Parse the the `sd-jwt` into a `jwt` + `disclosures`
3) Check that the holder's `key` is inside of the `jwt.cnf`
4) Select `some` of the `disclosures` for disclosure
5) Puts together the `jwt` + `some`
6) Constructs a `kb` jwt with the holder's `key`

In step (5), you can't serialize back the `jwt` from a parsed structure (e.g. JSON), because the parsing is non-invertible: you can't parse and serialize and go back to necessarily the same value, because of #531. So, that means, that, in step (2), you have to parse the `sd-jwt` but *also* keep the original base64url encoded value of the jwt, because you can't reconstruct it from a parsed structure.

Being opinionated about how JSON serialization is done (e.g. requiring the removal of whitespace) would make (i think) the parsing invertible and solve this problem.

Apologies for not being able to articulate this more clearly, but wanted to send this out in case someone is able to spot something wrong I might be doing while implementing a parser.

The environment in which I'm doing this is likely way more convoluted than an average holder , so it is also possible that even if this is a problem it could be marked as "not important enough because there are very few holders would run into this being a problem".

**Comment by bc-pi** [comment]
The requirement to save the various base64url parts (really the issuer-signed JWT and each of the disclosures) in order to [re]construct the SD-JWT[+KB] and present it is absolutely just a fundamental part of how this stuff works. It builds on and reuses constructs from JWS and JWE that recognize JSON's nondeterminism and avoids the complexities, interoperability problems, and security pitfalls of canonicalization by just base64url encoding and calculating integrity (signature, mac, hash) over that. 

There is undoubtedly some historical context and understanding here that isn't necessarily conveyed in this draft. But we've tried. https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-14.html#name-disclosure-format-considera for example has some treatment of these concepts. And statements like the one https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-14.html#section-4.2.3-2 try too. 

I'd be open to ideas about how to better convey these ideas. Within reason, of course. And also with consideration that the document in question has past last call (twice!).

**Comment by bc-pi** [comment]
"thanks! feel free to close as WAI if that's useful." - @samuelgoto in a conversation on slack
