### ISSUE TITLE
Define an content-type for the bas64url encoded artifacts in the HTTP Requests and Responses

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/oauth-selective-disclosure-jwt#74]
We should consider to define a content-type and returning this in the HTTP Response, may we imagine something like `application/sd-jwt-svc`?

and for the request `application/sd-jwt-release`

**Comment by Sakurann** [comment]
what is the use case when only SD-JWT is returned in HTTP Response?

**Comment by peppelinux** [comment]
During the issuance of a VC the VCI releases both SD-JWT and SVC, combined in a single artifact, this artifact should have a content-type, then the receiver is able to know what it is and process it in the right way.

I don't have any use-case with an issuance response with the sd-jwt alone

**Comment by Sakurann** [comment]
so application/sd-jwt+svc will be used during issuance request and application/sd-jwt-release will be used during presentation request? SGTM
(cc @bc-pi)

**Comment by bc-pi** [comment]
IMHO this is a bit premature and maybe unnecessary. Because I'd imagine these artifacts will most likely be used in places, such as within the JSON content of API messages or HTTP header, where a content/media type isn't relevant. 

It maybe makes sense for the case of the SD-JWT and SVC being returned together as the HTTP response content. I *still* (as mentioned previously including in Philly) think that the combined SD-JWT and SVC needs to be given it's own proper name and treatment as a first order thing in this draft though. And that should probably happen before defining a media type for it. ['+' has some special meaning in media types](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml#structured-syntax-suffix) so using it to mean "and" with `application/sd-jwt+svc` doesn't really work.

**Comment by Sakurann** [comment]
When SD-JWT is transported over OpenID4VC, content-type defined by OAuth or OpenID4VC specifications will be used - in those cases, there is no need to define a specific one whether credential format is sd-jwt or not.

If there are no other use-cases where sd-jwt is the only content of http req/res, suggest closing this issue

**Comment by Sakurann** [comment]
We discussed registering application/sd-jwt similar to a language defined in application/jose registration in [RFC7519](https://www.rfc-editor.org/rfc/rfc7515.html#section-9.2.1)

will open a separate issue on JOSE Header content-type (typ/cty parameters), also related to recent VC WG discussion.

**Comment by Sakurann** [comment]
PR #249 sufficiently addressed this.
